// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr4LPIfTfF1PpcreZ_w9ToDrjZaoFWINc',
    appId: '1:154156905359:web:bfea1f9e22d7b7b5c991fa',
    messagingSenderId: '154156905359',
    projectId: 'pyssyproject',
    authDomain: 'pyssyproject.firebaseapp.com',
    storageBucket: 'pyssyproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpB17-XGmM4iO5FBdMOJOE98zBxvUcj2c',
    appId: '1:154156905359:android:9c96245562abd53ec991fa',
    messagingSenderId: '154156905359',
    projectId: 'pyssyproject',
    storageBucket: 'pyssyproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzCAGSgFGGuX0sja_K9xeMJPOnj8GF9eM',
    appId: '1:154156905359:ios:233e11851780c658c991fa',
    messagingSenderId: '154156905359',
    projectId: 'pyssyproject',
    storageBucket: 'pyssyproject.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr4LPIfTfF1PpcreZ_w9ToDrjZaoFWINc',
    appId: '1:154156905359:web:cf5b777c9133e8e1c991fa',
    messagingSenderId: '154156905359',
    projectId: 'pyssyproject',
    authDomain: 'pyssyproject.firebaseapp.com',
    storageBucket: 'pyssyproject.firebasestorage.app',
  );
}
